# Generated by Django 5.1.4 on 2025-01-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanPlate_app', '0002_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
