# Generated by Django 5.1.4 on 2025-01-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PanPlate_app', '0003_video_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='watched',
        ),
    ]
